name = "humla"
type = "javascript"
account_id = "a5407b781bec5a58294d3dcaa2c18806"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
  { binding = "ASSETS", id = "5708240827844761a93e82f00abec273", preview_id = "5708240827844761a93e82f00abec273" },
  { binding = "ACTIONS", id = "caa1346db8af4d24a59dfc3834ae1bc0", preview_id = "caa1346db8af4d24a59dfc3834ae1bc0" },
]

[site]
bucket = "./public"
entry-point = "worker"

[build]
upload.format = "service-worker"
command = "deno bundle src/server/sw.ts worker/sw.js"
